# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zT1bJsL3YvdG2mdMsj_N6Kdpg_XS8MzP
"""

from wasabi import msg
from time import process_time as time

page = "Natural_Language_Processing"
print(f"Categories for `{page}`:")
t = time()
for c in wg.get_categories(page):
  print("\t", c)
  for cc in wg.get_categories(c):
    print("\t\t->", cc)
msg.good(f"Success in {time() - t:.2f}s")

from spacy import load as spacy_load
from spikex.wikigraph import load as wg_load
from spikex.pipes import WikiPageX

# load a spacy model and get a doc
nlp = spacy_load('en_core_web_sm')
doc = nlp('Elon Musk runs Tesla Motors')
# load a WikiGraph
wg = wg_load('enwiki_core')
# get a WikiPageX and extract all pages
wikipagex = WikiPageX(wg)
doc = wikipagex(doc)
# see all pages extracted from the doc
for span in doc._.wiki_spans:
  print(span)
  print(span._.wiki_pages)